import type { LucideIcon } from "lucide-react";
import { Coins, Gauge, Crown, PieChart, Award, Flame } from "lucide-react";

// Phase 3A — MPGR Agent frontend foundation. Everything here is local/mock:
// no OpenAI, Claude, Gemini, or backend calls. Replies are generated by
// simple keyword matching against the app's own feature set so the chat
// feels on-brand while the page is honest about being a local preview.
//
// Phase 3B swap point: `generateAgentReply` becomes the one function that
// gets replaced with a real model call; nothing else in this module or the
// hook/UI layer needs to change shape.

export type AgentStatusId = "online" | "thinking" | "beta";

export interface AgentStatusDef {
  id: AgentStatusId;
  label: string;
  dotClass: string;
  textClass: string;
  bgClass: string;
  ringClass: string;
  pulse?: boolean;
}

export const AGENT_STATUS: Record<AgentStatusId, AgentStatusDef> = {
  online: {
    id: "online",
    label: "Online",
    dotClass: "bg-primary",
    textClass: "text-primary-glow",
    bgClass: "bg-primary/10",
    ringClass: "ring-primary/20",
  },
  thinking: {
    id: "thinking",
    label: "Thinking",
    dotClass: "bg-gold",
    textClass: "text-gold",
    bgClass: "bg-gold/10",
    ringClass: "ring-gold/20",
    pulse: true,
  },
  beta: {
    id: "beta",
    label: "Beta",
    dotClass: "bg-primary-glow",
    textClass: "text-primary-glow",
    bgClass: "bg-primary/10",
    ringClass: "ring-primary/20",
  },
};

export interface AgentPromptSuggestion {
  id: string;
  label: string;
  prompt: string;
  icon: LucideIcon;
}

export const AGENT_PROMPT_SUGGESTIONS: AgentPromptSuggestion[] = [
  {
    id: "xp",
    label: "Check my XP progress",
    prompt: "How is my XP and level progress looking?",
    icon: Flame,
  },
  {
    id: "staking",
    label: "How do I stake MPGR?",
    prompt: "How do I stake MPGR and what are the lock options?",
    icon: Coins,
  },
  {
    id: "holder-tier",
    label: "What's my Holder Tier?",
    prompt: "What is my current Holder Tier and how do I level it up?",
    icon: Gauge,
  },
  {
    id: "premium",
    label: "Explain Premium benefits",
    prompt: "What benefits do I get from MPGR Premium?",
    icon: Crown,
  },
  {
    id: "portfolio",
    label: "Show my portfolio summary",
    prompt: "Give me a summary of my MPGR portfolio.",
    icon: PieChart,
  },
  {
    id: "season-pass",
    label: "Season Pass rewards?",
    prompt: "How do Season Pass rewards and levels work?",
    icon: Award,
  },
];

const FALLBACK_REPLIES = [
  "I'm running in local preview mode right now, so I can only point you in the right direction — full reasoning connects in a future phase. Try asking about XP, staking, Holder Tier, Premium, or your portfolio.",
  "That's outside what I can answer in this local preview. I can currently help with XP, staking, Holder Tier, Premium, and Season Pass questions.",
];

interface ReplyRule {
  keywords: string[];
  reply: string;
}

const REPLY_RULES: ReplyRule[] = [
  {
    keywords: ["xp", "level", "streak"],
    reply:
      "Your XP and level progress live on your Profile and Dashboard — daily check-ins, achievements, and referrals are the fastest ways to climb. Once I'm connected to live data, I'll be able to read your exact XP total and streak here.",
  },
  {
    keywords: ["stak", "lock"],
    reply:
      "Staking lets you lock MPGR for a chosen duration to earn rewards, shown on the Staking page along with your active positions and claimable rewards. Longer lock durations generally earn a stronger rate — head to Staking to see your live options.",
  },
  {
    keywords: ["holder", "tier"],
    reply:
      "Holder Tier is based on your combined wallet, staked, and locked MPGR — it drives your badge, governance voting weight, and community reputation. Check the Holder Tier section on your Dashboard or Profile to see your score and progress to the next tier.",
  },
  {
    keywords: ["premium", "subscription", "membership"],
    reply:
      "MPGR Premium boosts your XP and Rewards multipliers and unlocks premium cosmetics across the app. Visit the Premium page to compare tiers and see your current multiplier.",
  },
  {
    keywords: ["portfolio", "balance", "wallet"],
    reply:
      "Your Portfolio Overview on the Dashboard breaks down wallet, staked, and locked MPGR alongside claimable rewards. That's the best place to see your full holdings at a glance.",
  },
  {
    keywords: ["season", "pass"],
    reply:
      "The Season Pass tracks seasonal points toward level rewards shown on the Season Pass page. Play, stake, and stay active during the season to keep climbing the track.",
  },
  {
    keywords: ["reward", "claim"],
    reply:
      "Claimable rewards from staking, achievements, and events show up on the Rewards page. Anything claimable there is ready to collect right now.",
  },
  {
    keywords: ["hello", "hi", "hey"],
    reply: "Hey! I'm the MPGR Agent — ask me about your XP, staking, Holder Tier, Premium, or portfolio.",
  },
];

export function generateAgentReply(prompt: string): string {
  const normalized = prompt.toLowerCase();
  const match = REPLY_RULES.find((rule) => rule.keywords.some((kw) => normalized.includes(kw)));
  if (match) return match.reply;
  return FALLBACK_REPLIES[Math.floor(Math.random() * FALLBACK_REPLIES.length)];
}
